def start():
    a = ['B', 'L', 'I', 'S', 'S']
    for i in a:
        print(i)

start()

for i in range(0,10,2):
    print(i)

for(i=5;i>0;i--):
    print(i)

x = 4
y = 2 + 4 * 3 - x
z = [True, 2, 3, "abc", 5, 7]
if not x < 10:
    print(x)
    print(y)
else:
    if not(x < 5):
        x = x + 100
    else:
        x = x + 1000
        print(x)

def print_xy(x,y):
    if -y < 0:
        print(x+y)

print_xy(x,y)

print(z[0:3:2])
print(z[0::2])
# print(x)
print(z)
print(range(5))
print(range(1,5,2))
t = 3>0 and 4<0
print(t)

y = 3>0 or 0>3
print(y)

if 3>0 and 0>3:
    print("True")
